export const COMPONENT_KEYS = {
  transform: 'transform',
  collider: 'collider',
  character: 'character',
  movementIntent: 'movementIntent',
  movementImpulse: 'movementImpulse',
  navGrid: 'navGrid',
  skeletalModel: 'skeletalModel',
  meshDraws: 'meshDraws',
  staticModel: 'staticModel',
  childOf: 'childOf',
  children: 'children',
  localTransform: 'localTransform',
  boneAttachment: 'boneAttachment',
  animationClipMap: 'animationClipMap',
  animationStateMachine: 'animationStateMachine',
  cameraFollow: 'cameraFollow',
  renderable: 'renderable',
  renderGroup: 'renderGroup',
  skin: 'skin',
  gltfNodeIndex: 'gltfNodeIndex',
  groundPlane: 'groundPlane',
  health: 'health',
  combatIntent: 'combatIntent',
  weapon: 'weapon',
  projectile: 'projectile',
  equipmentSlots: 'equipmentSlots',
  rightHandStateMachine: 'rightHandStateMachine',
  leftHandStateMachine: 'leftHandStateMachine',
  rightHandClipMap: 'rightHandClipMap',
  leftHandClipMap: 'leftHandClipMap',
  animationHandMasks: 'animationHandMasks',
  animationAimOffset: 'animationAimOffset',
  animationPoseOverlay: 'animationPoseOverlay',
  animationFullBody: 'animationFullBody',
  destructible: 'destructible',
} as const;

export type ComponentKey = (typeof COMPONENT_KEYS)[keyof typeof COMPONENT_KEYS];
